### ISSUE TITLE
Declarative format

### ISSUE THREAD

**Issue by domenkozar** [NixHercules/hercules#4]
I'd essentially like to turn https://github.com/mayflower/hydra-jobs/blob/master/spec.json into something more `.travis.yml` alike. 

```yaml

inputs:
  src:
    type: git
    value: git://github.com/mayflower/hydra-jobs
  nixpkgs:
    type: git
    value: git://github.com/mayflower/nixpkgs.git

notifications:
  email:
    - devnull+hydra@mayflower.de
```
